In [31]:
import numpy as np
import pandas as pd

pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.3
numpy            : 1.24.4
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 56.0.0
pip              : 25.0.1
Cython           : None
pytest           : 6.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.2
pandas_datareader: None
bs4              : 4.12.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.9.0
gcsfs            : None
matplotlib       : 3.7.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 13.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 2.0.36
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : 0.23.0
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

In [32]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [33]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [34]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2013-01-01  1.752617 -1.563886 -0.424161 -0.547066
2013-01-02  1.258815 -1.879826  0.486040 -0.457800
2013-01-03  2.702998 -0.305122 -2.491232 -1.292543
2013-01-04 -0.425900  0.911922  0.052108 -0.844296
2013-01-05  0.510430 -0.487296  0.950646  0.556505
2013-01-06 -0.112669 -1.378818 -0.012247 -0.566647

In [35]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'}) 
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [36]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [37]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [38]:
df.head()

                   A         B         C         D
2013-01-01  1.752617 -1.563886 -0.424161 -0.547066
2013-01-02  1.258815 -1.879826  0.486040 -0.457800
2013-01-03  2.702998 -0.305122 -2.491232 -1.292543
2013-01-04 -0.425900  0.911922  0.052108 -0.844296
2013-01-05  0.510430 -0.487296  0.950646  0.556505

In [39]:
df.tail(3)

                   A         B         C         D
2013-01-04 -0.425900  0.911922  0.052108 -0.844296
2013-01-05  0.510430 -0.487296  0.950646  0.556505
2013-01-06 -0.112669 -1.378818 -0.012247 -0.566647

In [40]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [41]:
4+5

9

In [42]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [43]:
df.to_numpy()

array([[ 1.75261655, -1.56388564, -0.42416079, -0.54706594],
       [ 1.25881507, -1.87982553,  0.4860399 , -0.45779987],
       [ 2.7029976 , -0.30512239, -2.49123194, -1.29254276],
       [-0.42590035,  0.91192153,  0.05210796, -0.84429586],
       [ 0.51042996, -0.48729635,  0.95064618,  0.55650495],
       [-0.1126689 , -1.3788179 , -0.01224703, -0.56664687]])

In [44]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [45]:
# create a dataframe with geo-numeric data
data = pd.DataFrame({'region': ['east', 'west', 'north', 'south'],
                     'gdp': [2000, 3245, 3421, 2099]})
data['gdp']

0    2000
1    3245
2    3421
3    2099
Name: gdp, dtype: int64

In [46]:
data.columns

Index(['region', 'gdp'], dtype='object')

In [47]:
data.iloc(0)

In [48]:
for x in data.iloc[0]:
    print(x)

east
2000

In [49]:
data['gdp'] = 2 * data['gdp']

In [50]:
data['gdp']

0    4000
1    6490
2    6842
3    4198
Name: gdp, dtype: int64

In [51]:
# sorting on a Dataframe
data.sort_values(by='gdp', ascending=False)

  region   gdp
2  north  6842
1   west  6490
3  south  4198
0   east  4000

In [52]:
gdp = data.gdp.iloc[:]
gdp

0    4000
1    6490
2    6842
3    4198
Name: gdp, dtype: int64

In [53]:
np.average(gdp, axis=0)

5382.5